### ISSUE TITLE
Implement the ability to add text in the Outlook "Location" field

### ISSUE THREAD

**Issue by kenneth-edwall** [diggsweden/jitsi-outlook#40]
### Contact Details

@kenneth-edwall

### What benefits does the suggestion solve?

This is a common feature in other meeting services that provides an outlook plugin. The "Location" field is a required field prior to sending a calendar invite. So if the field is blank Outlook will ask you whether you want to send the invite or not with a blank location field.

Instead of requering the end user put the information there manually the plugin could do it for them. E.g "Jitsi meeting" or "My meeting service"

### Feature suggestion description

Add logic in the plugin to fetch a variable that populates the Location field. Make it so that the variable can be configured by the administrator, preferably via e.g an xml or json file that the plugin reads.

The solution must accept åäö characters

**Comment by Ayko1595** [comment]
This sounds like a good improvement to the plugin!

**Comment by Philldomd** [comment]
I have a solution for this, i will create a pull request for it in the upcoming days

**Comment by Philldomd** [comment]
Awaiting approval on my other pull-request so that i can merge this change as it will introduce an Office call utility. So a lot of the code from my other commits have changed to the new file. Also added new test cases for Office Mock calls and altered package.json and jest.config.js for this to work.
